version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/cypress-cucumber-preprocessor-single-steps
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: link the package
          command: |
            npm link
            npm link cypress-cucumber-preprocessor-single-steps
      - run:
          name: run tests
          command: npm test
      - run:
          name: release
          command: npm run semantic-release || true
